development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://h:p7690dae403eb8906b87ccff47362d772f58627e8ae817b406328760372d7b49f@ec2-34-226-62-155.compute-1.amazonaws.com:29579" } %>
  channel_prefix: mod4-project_production
